export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'

// Twitter
export const RECEIVE_TIMELINE = 'RECEIVE_TIMELINE'
export const ADD_TWEET = 'ADD_TWEET'

// LocalStorage
export const SAVE_LOCALSTORAGE = 'SAVE_LOCALSTORAGE'

